services:
  - type: web
    name: simulador-mz
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
